---
title: "Special-Amulets"
author: "A book series for 10-year-olds"
output: 
  html_document: 
    keep_md: yes
    toc: yes
---


## Premise
Two young siblings own amulets from their mysterious and adventurous great Grandmother. When they touch them together they transport to some new place either from their Grandma's many travels, the burgeoning legends about her, or one of her whymsical science fiction stories that she made up to pass the time on long voyages. When they are transported their amulets leave them and they must find them in order to get back home. Somehow there are always just enough clues to find them while learning a bit more about their extraordinary Granny Florence.

### Characters
#### Daniel 
A ten-year-old boy. Too serious at times for his age. A good boy in general, but can sometimes be a bit prideful.

#### Sophie
Daniel's eight-and-a-half-year-old sister. Bright-eyed and curious. Can get ahead of herself. Gets into trouble. Sometimes on purpose just to see what happens.

#### Granny Florence
Not really a character in the story, but someone Daniel and Sophie have an insatiable craving to find out about. See the backstory for some info about her.

## Story structure
There is a backstory to this whole thing, but it isn't in any book. The books are episodic, so they can be read in the wrong order without too much problems. But here's the backstory so you can refer to it properly.

### The backstory
Daniel and Sohpie's great grandmother Florence was an adventurous woman who toured the world all the way back when it required a steamship to do so. (Well she started out on a steamship. She was going hard-core until the day she died, which was relatively recent.) It's hard to parse out what is fact and what is legend and what is from her wild imagination. She didn't write any memoirs and she left no will, so all of her exotic posessions were quickly sold off when she died. There must have been a grandfather at some point, but he isn't really so important to the story. Perhaps he died early on. Daniel and Sophie both have precious few memories of this extraordinary woman and one of those memories is when she gave them each an amulet when they were very young. They remember a mysterious twinkle in her eye as she giddily put them around their necks. Their mother kept them in her jewelry box for safe keeping. Granny Florence died soon after. The amulets stayed hidden  for many years, but on Daniel's tenth birthday he received a gift that sparked his memory of it and he asked his mother for his. Figuring they were now old enough to take care of it, she retrieved the amulets and gave them to Daniel and Sophie. Daniel's was blue and Sophie's violet. They loved these mysterious connections to the past and to their mysterious great grandmother. A few months later while building a tall block tower together, they both noticed their amulets hanging at a slight tilt toward each other like they wanted to touch. The amulets weren't magnetic to anything else (they tried), so they found this odd. They decided to let them touch and stick together and suddenly a bright light burst out from the connection. Daniel's hand jolted out in surprise and he knocked over the tower. The next thing they knew they were opening their eyes in a strange room. Daniel was sitting in a wicker chair and Sophie was leaning against a wooden desk. They both instinctively felt for their amulets, but found they had come off. The room had a dinged metal bed in one corner with a round bedside table next to it. On the table was a lamp that looked modern enough, but was lit with kerosene. It was still lit even though sunlight streamed through the cracks in the closed shutters. On the table next to the lamp was a stand-up photo of their great grandmother and next to it the two amulets. Daniel and Sophie couldn't be sure of the photo since the woman was so young, but her wry smile did look so much like Granny Florence's. They walked over together and retrieved their amulets. They put them over their necks and touched the stones again both independently hoping this would take them back. Another flash of light and they were back in their room where they immediately heard the crash of the toppling block tower. 

## Limits and rules
* Keep it at a 10-year-old vocab reading level.
* Word limit on chapters is xx words.
* Word limit on whole books is xx words.
* Keep it episodic for the most part so each book stands on its own.

## Mechanics for publishing
1. Copy the template.
2. Write your own story.
3. Add to Books in progress to get some editing help.
4. When final convert to epub.
5. Add to Finished books

There's a brainstorming sheet to get ideas from and leave ideas. Cross them out when they've been used.


## Who made this thing?
I did! I admit it! I made it with my ten-year-old son. Here's the thing. He's just learning how to read chapter books and to encourage him, I bought him a kindle for Christmas. I thought this would open up a whole new world of literature. Nope. He only wants to read one thing. This series which I will not name here, but let's call it Boogeyman. In fact, I think he genuinely tries to read other books, but none seem to come close to holding his attention like Boogeyman. Boogeyman from what I can tell is incredibly formulaic. The books are very manageable, so he can read one in like two hours. So I say, "sure let's get you the next one of those." There's over 50 of these things. I look on Amazon. 5 bucks! I bought one. He consumed it before lunch and asked for another. I quickly realized I could not sustain this level of consumption. Now I see what a genius this author is.

So I thought, what the heck. Maybe we can make a fun project out of this and other kids with e-readers can enjoy it for free. And then I thought hm, maybe some other dads or moms with kids wouldn't mind contributing a few words. So we came up with a flexible premise (my son thought up the amulets and the names) and I put it here. If you're so inclined to try writing something, welcome!
